const COLORS={red:'Rouge',yellow:'Jaune',violet:'Violet',gray:'Gris',brown:'Urgentiste',green:'Chirurgien',blue:'Anesthésiste'};
const icons={
  brown:`<svg class="med-icon" viewBox="0 0 48 48" aria-label="Stéthoscope"><path d="M13 8v10a9 9 0 0 0 18 0V8"/><path d="M9 8h8M27 8h8M22 28v3a8 8 0 0 0 16 0v-2"/><circle cx="38" cy="25" r="4"/></svg>`,
  green:`<svg class="med-icon" viewBox="0 0 48 48" aria-label="Bistouri"><path d="M7 41l3 2 19-21-3-4z"/><path d="M26 18L39 2v5c-1 6-5 12-10 15z" fill="white"/><path d="M10 39l17-19"/></svg>`,
  blue:`<svg class="med-icon" viewBox="0 0 48 48" aria-label="Seringue"><path d="M14 29l15-15 7 7-15 15z"/><path d="M33 18L44 7M10 25l5 5M20 35l5 5M17 33L9 41M5 37l8 8"/><path d="M19 29l4 4M22 26l4 4M25 23l4 4"/></svg>`
};
const CHARACTERS=[['Pascal','pascal-pirate.png'],['Mathieu','mathieu-luchador.png'],['Pierre','pierre-halloween.png'],['Adela','adela-egyptienne.png'],['JB','jb-cosmonaute.png'],['Romain','romain-poulet.png'],['Natacha','natacha-princesse.png'],['Fanny','fanny-exploratrice.png'],['Félix','felix-cyborg.png'],['Youri','youri-paladin.png'],['Quentin','quentin-dictateur.png'],['Nicolas','nicolas-vigilante.png'],['Yannick','yannick-cardinal.png'],['Cecilia','cecilia-infirmiere.png'],['Thibault','thibault-aventurier.png'],['Polo','polo-dandy.png'],['Édouard','edouard-aviateur.png'],['Justin','justin-judoka.png'],['Charlotte','charlotte-cavaliere.png'],["Catoire d’Arabie",'catoire-arabie.png'],['Rémy','remy-shaolin.png'],['Olivier','olivier-policier.png'],['Raphaël','raphael-scaphandrier.png'],['Éric','eric-druide.png'],['Cyril','cyril-alchimiste.png'],['Rémi','remi-berserker.png'],['Thomas','thomas-capitaine-sous-marin.png'],['Benjamin','benjamin-sherif.png'],['Edwin','edwin-zadiste.png'],['Alexandre','alexandre-hercule-satan.png'],['Erwan','erwan-bucheron.png']];
const $=id=>document.getElementById(id);let socket,state,session=JSON.parse(localStorage.getItem('duel-session')||'null'),lastChatCount=0,reconnectTimer=null,connectionNumber=0;
const invitedCode=new URLSearchParams(location.search).get('join')?.trim().toUpperCase().replace(/[^A-Z2-9]/g,'').slice(0,5)||'';
// Un joueur qui actualise son lien d'invitation doit conserver son identité.
// On oublie l'ancienne session uniquement si le lien vise une autre salle.
if(invitedCode&&session?.code!==invitedCode){session=null;localStorage.removeItem('duel-session')}
const special=c=>['brown','green','blue'].includes(c);const normalizedCharacter=name=>name==='Adéla'?'Adela':name;const characterFile=name=>CHARACTERS.find(c=>c[0]===normalizedCharacter(name))?.[1]||CHARACTERS[0][1];
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dieHTML(d,clickable=false){if(d.hidden)return `<button class="die back" disabled></button>`;const face=special(d.color)&&d.face==='symbol'?icons[d.color]:d.face==='flag'?'<span class="flag">⚑</span>':`<span class="value">${d.face??'?'}</span>`;return `<button class="die ${d.color} ${clickable?'clickable':''}" ${clickable?`data-die="${d.id}"`:''}>${face}</button>`}
function connect(){
  clearTimeout(reconnectTimer);const attempt=++connectionNumber,protocol=location.protocol==='https:'?'wss':'ws';
  $('connectionBanner').classList.toggle('hidden',!state);const nextSocket=new WebSocket(`${protocol}://${location.host}`);socket=nextSocket;
  nextSocket.onopen=()=>{if(attempt!==connectionNumber)return nextSocket.close();$('connectionStatus').textContent='Serveur connecté.';$('connectionBanner').classList.add('hidden');if(session?.code&&session?.playerId)send('join',{code:session.code,playerId:session.playerId})};
  nextSocket.onclose=()=>{if(attempt!==connectionNumber)return;$('connectionStatus').textContent='Connexion perdue — resynchronisation…';$('connectionBanner').classList.toggle('hidden',!state);reconnectTimer=setTimeout(connect,1500)};
  nextSocket.onmessage=e=>{if(attempt!==connectionNumber)return;const m=JSON.parse(e.data);if(m.type==='session'){session={code:m.code,playerId:m.playerId};localStorage.setItem('duel-session',JSON.stringify(session))}if(m.type==='state'){state=m.state;$('connectionBanner').classList.add('hidden');render()}if(m.type==='left')returnHome();if(m.type==='closed'){alert(m.message);returnHome()}if(m.type==='error')showError(m.message)}
}
function resynchronize(){if(document.visibilityState!=='visible')return;if(!socket||socket.readyState!==WebSocket.OPEN){connect();return}if(session?.code&&session?.playerId)send('join',{code:session.code,playerId:session.playerId})}
function send(type,payload={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...payload}));else showError('Le serveur n’est pas encore connecté.')}
function identity(){const c=CHARACTERS[Number($('characterSelect').value)];return{name:c[0],character:c[0]}}
function createRoom(){const who=identity();if(who){session=null;localStorage.removeItem('duel-session');send('create',{...who,rounds:Number($('roundCount').value)})}}
function createOrganizer(){session=null;localStorage.removeItem('duel-session');send('create',{name:'Organisateur',organizer:true,rounds:Number($('roundCount').value)})}
function joinRoom(){const who=identity(),code=$('roomCodeInput').value.trim().toUpperCase();if(who&&code){session=null;localStorage.removeItem('duel-session');send('join',{...who,code})}else if(who)showError('Indiquez le code de la salle.')}
function joinSpectatorRoom(){const code=$('roomCodeInput').value.trim().toUpperCase();if(!code)return showError('Indiquez le code de la salle.');session=null;localStorage.removeItem('duel-session');send('join',{code,spectator:true})}
function invitationUrl(){const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('join',state.code);return url.toString()}
function invitationText(){return `Je t’invite à jouer à Duel Urgensses ! Rejoins directement ma partie : ${invitationUrl()}`}
async function copyInvitation(){try{await navigator.clipboard.writeText(invitationUrl());$('copyInviteButton').textContent='LIEN COPIÉ !';setTimeout(()=>$('copyInviteButton').textContent='COPIER LE LIEN',1400)}catch{showError('Impossible de copier le lien sur cet appareil.')}}
async function shareInvitation(){if(navigator.share){try{await navigator.share({title:'Duel Urgensses',text:'Je t’invite à jouer à Duel Urgensses !',url:invitationUrl()});return}catch(error){if(error.name==='AbortError')return}}await copyInvitation()}
function showError(message){$('connectionStatus').textContent=message;$('connectionStatus').classList.add('error');setTimeout(()=>$('connectionStatus').classList.remove('error'),2500)}
async function showLeaderboard(){
  $('leaderboardDialog').showModal();$('leaderboardBody').innerHTML='<p class="leaderboard-loading">Chargement du classement…</p>';
  try{const response=await fetch('/api/leaderboard',{cache:'no-store'});if(!response.ok)throw new Error();const rows=await response.json();$('leaderboardBody').innerHTML=rows.length?`<div class="leaderboard-table"><div class="leaderboard-row leaderboard-head"><span>RANG</span><span>PERSONNAGE</span><span>V</span><span>PARTIES</span><span>TAUX</span><span>POINTS</span></div>${rows.map((r,i)=>`<div class="leaderboard-row"><b class="rank">${i+1}</b><span class="leaderboard-character"><img src="assets/characters/${characterFile(r.character)}" alt=""><strong>${esc(r.character)}</strong></span><b>${r.wins}</b><span>${r.games}</span><span>${r.winRate}%</span><span>${r.points}</span></div>`).join('')}</div>`:'<p class="leaderboard-empty">Le Hall of Fame attend sa première partie terminée.</p>'}catch{$('leaderboardBody').innerHTML='<p class="leaderboard-empty">Le classement est momentanément indisponible.</p>'}
}
function showGallery(){
  $('galleryGrid').innerHTML=CHARACTERS.map(([name,file])=>`<article class="gallery-card"><div><img src="assets/characters/${file}" alt="${esc(name)}" loading="lazy"></div><h3>${esc(name)}</h3></article>`).join('');
  $('galleryDialog').showModal();
}
function returnHome(){localStorage.removeItem('duel-session');session=null;state=null;const url=new URL(location.href);url.search='';url.hash='';location.href=url.toString()}
function render(){$('lobby').classList.toggle('hidden',!!state);$('waitingRoom').classList.toggle('hidden',!state||state.status!=='lobby');$('game').classList.toggle('hidden',!state||state.status==='lobby');$('chatPanel').classList.toggle('hidden',!state);$('leaveButton').classList.toggle('hidden',!state);$('spectatorModeNotice').classList.toggle('hidden',!state||state.viewerRole!=='spectator'||state.status==='lobby');renderChat();if(state.status==='lobby')return renderWaiting();renderGame()}
function renderWaiting(){$('copyCode').textContent=state.code;$('whatsappInviteLink').href=`https://wa.me/?text=${encodeURIComponent(invitationText())}`;const spectators=state.spectators.map(s=>`<div class="waiting-player spectator"><span class="spectator-icon">👁</span><span><b>${esc(s.name)}</b><small>ORGANISATEUR / SPECTATEUR${s.id===state.hostId?' · HÔTE':''}</small></span><i class="${s.connected?'online':''}"></i></div>`).join('');$('waitingPlayers').innerHTML=spectators+state.players.map(p=>`<div class="waiting-player"><img src="assets/characters/${characterFile(p.character)}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.character)}${p.id===state.hostId?' · HÔTE':''}</small></span><i class="${p.connected?'online':''}"></i></div>`).join('');const host=state.viewerId===state.hostId;$('onlineStartButton').classList.toggle('hidden',!host);$('waitingHint').textContent=host?(state.players.length<2?'En attente d’au moins deux joueurs actifs…':`${state.players.length} joueurs prêts. Vous pouvez lancer la partie.`):"L’hôte lancera la partie lorsque tout le monde sera prêt."}
function renderChat(){if(!state)return;const box=$('chatMessages'),atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<40;box.innerHTML=state.chat.map(m=>`<div class="chat-message ${m.role==='spectator'?'spectator':''}"><b>${esc(m.sender)}</b><span>${esc(m.text)}</span></div>`).join('')||'<p class="chat-empty">Le chat est ouvert. Soyez le premier à parler.</p>';if(atBottom)box.scrollTop=box.scrollHeight;if(state.chat.length>lastChatCount&&$('chatPanel').classList.contains('collapsed'))$('chatBadge').textContent=String(state.chat.length-lastChatCount);lastChatCount=state.chat.length}
function legalIds(){const me=state.players.find(p=>p.id===state.viewerId);if(!me||state.phase!=='play'||state.players[state.turn]?.id!==state.viewerId)return new Set();if(!state.leadColor)return new Set(me.dice.map(d=>d.id));const matching=me.dice.filter(d=>d.color===state.leadColor);return new Set((matching.length?[...matching,...me.dice.filter(d=>special(d.color))]:me.dice).map(d=>d.id))}
function renderGame(){const legal=legalIds();$('roundValue').textContent=`${state.round} / ${state.totalRounds}`;$('trickValue').textContent=`${state.trick} / ${state.round}`;$('leadColor').textContent=state.leadColor?COLORS[state.leadColor].toUpperCase():'—';$('phaseValue').textContent={bids:'PARIS',play:'LANCER',result:'RÉSULTAT',over:'TERMINÉ'}[state.phase]||state.phase;$('game').dataset.phase=state.phase;$('playersGrid').dataset.count=state.players.length;
  $('playersGrid').innerHTML=state.players.map((p,i)=>{const active=i===state.turn&&['bids','play'].includes(state.phase),mine=p.id===state.viewerId,side=i%2?'right-avatar':'left-avatar';return `<article class="player-card ${active?'active':''} ${mine?'is-me':''}"><div class="turn-indicator"><span>${mine?'À VOUS DE JOUER':'À SON TOUR'}</span><b>▼</b></div><div class="avatar-zone ${side}" aria-hidden="true"><div class="avatar-aura"></div><img class="character-sprite" src="assets/characters/${characterFile(p.character)}" alt=""><div class="avatar-shadow"></div></div><div class="player-head"><h3>${esc(p.name)}</h3><strong>${p.score}</strong></div><div class="metrics"><span>PARI <b>${p.bid??'—'}</b></span><span>PLIS <b>${p.tricks}</b></span>${mine?'<span>VOUS</span>':''}</div><div class="dice-rack">${p.dice.map(d=>dieHTML(d,legal.has(d.id))).join('')}</div>${p.connected?'':'<small class="disconnected">HORS CONNEXION</small>'}</article>`}).join('');document.querySelectorAll('[data-die]').forEach(el=>el.onclick=()=>send('play',{dieId:el.dataset.die}));$('playedDice').innerHTML=state.played.map(x=>`<div class="played-slot">${dieHTML(x.die)}<small>${esc(state.players[x.player].name)}</small></div>`).join('');$('bidControls').innerHTML='';$('nextButton').classList.add('hidden');$('resetButton').classList.add('hidden');$('newRoomButton').classList.add('hidden');const turnPlayer=state.players[state.turn],myTurn=turnPlayer?.id===state.viewerId;
  if(state.phase==='bids'){$('message').innerHTML=`<strong>PARI DE ${esc(turnPlayer.name.toUpperCase())}</strong><br><span>${myTurn?'Choisissez le nombre de plis que vous allez remporter.':'En attente de son pari…'}</span>`;if(myTurn){$('bidControls').innerHTML=Array.from({length:state.round+1},(_,n)=>`<button data-bid="${n}">${n}</button>`).join('');document.querySelectorAll('[data-bid]').forEach(el=>el.onclick=()=>send('bid',{bid:+el.dataset.bid}))}}
  if(state.phase==='play')$('message').innerHTML=`<strong>AU TOUR DE ${esc(turnPlayer.name.toUpperCase())}</strong><br><span>${myTurn?'Choisissez maintenant l’un de vos dés illuminés.':'Son choix apparaîtra ici.'}</span>`;if(state.phase==='result'){$('message').textContent=`Pli remporté par ${state.players[state.leader].name}.`;$('nextButton').classList.toggle('hidden',state.players[state.leader].id!==state.viewerId)}if(state.phase==='over'){const max=Math.max(...state.players.map(p=>p.score)),winners=state.players.filter(p=>p.score===max).map(p=>p.name);$('message').textContent=winners.length>1?`Égalité : ${winners.join(' et ')}.`:`${winners[0]} remporte le duel !`;$('playedDice').innerHTML='<strong>DUEL TERMINÉ</strong>';const host=state.viewerId===state.hostId;$('resetButton').classList.toggle('hidden',!host);$('newRoomButton').classList.toggle('hidden',!host)}renderMobileStage()}
function renderMobileStage(){
  const me=state.players.find(p=>p.id===state.viewerId),turnPlayer=state.players[state.turn],myTurn=turnPlayer?.id===state.viewerId,legal=legalIds(),played=state.played.map(x=>`<div class="mobile-played-die">${dieHTML(x.die)}<small>${esc(state.players[x.player].name)}</small></div>`).join('');
  const hand=me?me.dice.map(d=>dieHTML(d,state.phase==='play'&&legal.has(d.id))).join(''):'';let title='',instruction='',actions='';
  if(state.phase==='bids'){title=myTurn?'À VOUS DE PARIER':`${turnPlayer.name} prépare son pari`;instruction=myTurn?'Combien de plis pensez-vous remporter ? Appuyez simplement sur un nombre.':'Patientez un instant. Vos dés restent visibles ci-dessous.';if(myTurn)actions=`<div class="mobile-big-actions">${Array.from({length:state.round+1},(_,n)=>`<button data-mobile-bid="${n}">${n}<small>pli${n>1?'s':''}</small></button>`).join('')}</div>`}
  if(state.phase==='play'){title=myTurn?'À VOUS DE JOUER':`Au tour de ${turnPlayer.name}`;instruction=myTurn?'Appuyez sur l’un des dés illuminés. Les autres sont interdits pour ce pli.':'Le dé joué apparaîtra automatiquement ici.'}
  if(state.phase==='result'){const winner=state.players[state.leader];title=`${winner.name} remporte le pli`;instruction=winner.id===state.viewerId?'Vous avez la main pour continuer.':'Le vainqueur va lancer le pli suivant.';if(winner.id===state.viewerId)actions='<button class="mobile-continue" data-mobile-next>PLI SUIVANT</button>'}
  if(state.phase==='over'){const max=Math.max(...state.players.map(p=>p.score)),winners=state.players.filter(p=>p.score===max).map(p=>p.name),host=state.viewerId===state.hostId;title=winners.length>1?'Égalité !':`${winners[0]} gagne !`;instruction='La partie est terminée.';if(host)actions='<button class="mobile-continue" data-mobile-reset>REJOUER AVEC LES MÊMES</button><button class="mobile-new-room" data-mobile-new-room>NOUVELLE SALLE</button>'}
  const avatars=state.players.map((p,i)=>`<div class="mobile-avatar ${i===state.turn&&['bids','play'].includes(state.phase)?'active':''} ${p.id===state.viewerId?'is-me':''}"><img src="assets/characters/${characterFile(p.character)}" alt="${esc(p.name)}"><small>${esc(p.name)}</small></div>`).join('');
  $('mobileStage').innerHTML=`<div class="mobile-step"><span>ÉTAPE EN COURS</span><h2>${esc(title)}</h2><p>${esc(instruction)}</p></div>${played?`<div class="mobile-block"><h3>DÉS JOUÉS</h3><div class="mobile-played">${played}</div></div>`:''}${me&&state.phase!=='over'?`<div class="mobile-block mobile-hand"><h3>VOS DÉS</h3><div class="mobile-dice">${hand}</div></div>`:''}${actions}<div class="mobile-avatar-dock">${avatars}</div>`;
  document.querySelectorAll('[data-mobile-die]').forEach(()=>{});$('mobileStage').querySelectorAll('[data-die]').forEach(el=>el.onclick=()=>send('play',{dieId:el.dataset.die}));$('mobileStage').querySelectorAll('[data-mobile-bid]').forEach(el=>el.onclick=()=>send('bid',{bid:+el.dataset.mobileBid}));$('mobileStage').querySelector('[data-mobile-next]')?.addEventListener('click',()=>send('next'));$('mobileStage').querySelector('[data-mobile-reset]')?.addEventListener('click',()=>send('reset'));$('mobileStage').querySelector('[data-mobile-new-room]')?.addEventListener('click',()=>send('newRoom'));
}
function init(){
  const options=CHARACTERS.map(([name],i)=>`<option value="${i}">${name}</option>`).join('');$('characterSelect').innerHTML=options;
  if(invitedCode){$('roomCodeInput').value=invitedCode;$('invitedRoomCode').textContent=invitedCode;$('inviteNotice').classList.remove('hidden');$('joinButton').textContent='REJOINDRE LA PARTIE';$('lobby').classList.add('invited-lobby')}
  $('createButton').onclick=createRoom;$('organizerButton').onclick=createOrganizer;$('joinButton').onclick=joinRoom;$('joinSpectatorButton').onclick=joinSpectatorRoom;$('roomCodeInput').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'');$('roomCodeInput').onkeydown=e=>{if(e.key==='Enter')joinRoom()};
  $('onlineStartButton').onclick=()=>send('start');$('nextButton').onclick=()=>send('next');$('resetButton').onclick=()=>send('reset');$('newRoomButton').onclick=()=>send('newRoom');$('leaveButton').onclick=()=>{if(confirm('Quitter cette partie et revenir à l’accueil ?'))send('leave')};$('cancelWaitingButton').onclick=()=>send('leave');$('shareInviteButton').onclick=shareInvitation;$('copyInviteButton').onclick=copyInvitation;$('copyCode').onclick=async()=>{await navigator.clipboard.writeText(state.code);$('copyCode').textContent='COPIÉ !';setTimeout(()=>$('copyCode').textContent=state.code,1000)};
  $('chatHeader').onclick=()=>{$('chatPanel').classList.toggle('collapsed');$('chatBadge').textContent=''};
  $('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value.trim();if(text){send('chat',{text});$('chatInput').value=''}};
  $('rulesButton').onclick=()=>$('rulesDialog').showModal();$('closeRules').onclick=()=>$('rulesDialog').close();$('legend').innerHTML=['brown','green','blue'].map(c=>`<div class="legend-item">${dieHTML({color:c,face:'symbol'})}<span>${COLORS[c]}</span></div>`).join('');connect()
  $('leaderboardButton').onclick=showLeaderboard;$('closeLeaderboard').onclick=()=>$('leaderboardDialog').close();
  $('galleryButton').onclick=showGallery;$('closeGallery').onclick=()=>$('galleryDialog').close();document.addEventListener('visibilitychange',resynchronize);window.addEventListener('online',resynchronize);
}
init();
