const COLORS={red:'Rouge',yellow:'Jaune',violet:'Violet',gray:'Gris',brown:'Urgentiste',green:'Chirurgien',blue:'Anesthésiste'};
const icons={brown:`<svg class="med-icon" viewBox="0 0 48 48"><path d="M10 16h28v20H10zM18 16v-5h12v5M18 25h12M24 19v12"/><path d="M7 21h3M38 21h3"/></svg>`,green:`<svg class="med-icon" viewBox="0 0 48 48"><path d="M9 12h30v24H9zM19 12v24M30 12v24M9 20h30"/><path d="M23 26l8-8M26 31l9-9M31 32l4-4"/></svg>`,blue:`<svg class="med-icon" viewBox="0 0 48 48"><path d="M15 17c2-5 16-5 18 0l3 12c-3 7-21 7-24 0z"/><path d="M18 20c4 3 8 3 12 0M24 33v7M24 40h10M36 40c3 0 5-2 5-5v-7"/></svg>`};
const CHARACTERS=[['Pascal','pascal-pirate.png'],['Mathieu','mathieu-luchador.png'],['Pierre','pierre-halloween.png'],['Adéla','adela-egyptienne.png'],['JB','jb-cosmonaute.png'],['Romain','romain-poulet.png'],['Natacha','natacha-princesse.png'],['Fanny','fanny-exploratrice.png'],['Félix','felix-cyborg.png'],['Youri','youri-paladin.png'],['Quentin','quentin-dictateur.png'],['Nicolas','nicolas-vigilante.png'],['Yannick','yannick-cardinal.png'],['Cécilia','cecilia-infirmiere.png'],['Thibault','thibault-aventurier.png'],['Polo','polo-dandy.png'],['Édouard','edouard-aviateur.png'],['Justin','justin-judoka.png'],['Charlotte','charlotte-cavaliere.png'],["Catoire d’Arabie",'catoire-arabie.png'],['Rémy','remy-shaolin.png'],['Olivier','olivier-policier.png'],['Raphaël','raphael-scaphandrier.png'],['Éric','eric-druide.png']];
const $=id=>document.getElementById(id);let socket,state,session=JSON.parse(localStorage.getItem('duel-session')||'null'),lastChatCount=0;
const special=c=>['brown','green','blue'].includes(c);const characterFile=name=>CHARACTERS.find(c=>c[0]===name)?.[1]||CHARACTERS[0][1];
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dieHTML(d,clickable=false){if(d.hidden)return `<button class="die back" disabled></button>`;const face=special(d.color)&&d.face==='symbol'?icons[d.color]:d.face==='flag'?'<span class="flag">⚑</span>':`<span class="value">${d.face??'?'}</span>`;return `<button class="die ${d.color} ${clickable?'clickable':''}" ${clickable?`data-die="${d.id}"`:''}>${face}</button>`}
function connect(){const protocol=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${protocol}://${location.host}`);socket.onopen=()=>{$('connectionStatus').textContent='Serveur connecté.';if(session?.code&&session?.playerId)send('join',{code:session.code,playerId:session.playerId})};socket.onclose=()=>{$('connectionStatus').textContent='Connexion perdue — nouvelle tentative…';setTimeout(connect,1500)};socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='session'){session={code:m.code,playerId:m.playerId};localStorage.setItem('duel-session',JSON.stringify(session))}if(m.type==='state'){state=m.state;render()}if(m.type==='error')showError(m.message)}}
function send(type,payload={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...payload}));else showError('Le serveur n’est pas encore connecté.')}
function identity(){const c=CHARACTERS[Number($('characterSelect').value)];return{name:c[0],character:c[0]}}
function createRoom(){const who=identity();if(who){session=null;localStorage.removeItem('duel-session');send('create',{...who,rounds:Number($('roundCount').value)})}}
function createOrganizer(){session=null;localStorage.removeItem('duel-session');send('create',{name:'Organisateur',organizer:true,rounds:Number($('roundCount').value)})}
function joinRoom(){const who=identity(),code=$('roomCodeInput').value.trim().toUpperCase();if(who&&code){session=null;localStorage.removeItem('duel-session');send('join',{...who,code})}else if(who)showError('Indiquez le code de la salle.')}
function showError(message){$('connectionStatus').textContent=message;$('connectionStatus').classList.add('error');setTimeout(()=>$('connectionStatus').classList.remove('error'),2500)}
function render(){$('lobby').classList.toggle('hidden',!!state);$('waitingRoom').classList.toggle('hidden',!state||state.status!=='lobby');$('game').classList.toggle('hidden',!state||state.status==='lobby');$('chatPanel').classList.toggle('hidden',!state);$('leaveButton').classList.toggle('hidden',!state);renderChat();if(state.status==='lobby')return renderWaiting();renderGame()}
function renderWaiting(){$('copyCode').textContent=state.code;const spectators=state.spectators.map(s=>`<div class="waiting-player spectator"><span class="spectator-icon">👁</span><span><b>${esc(s.name)}</b><small>ORGANISATEUR / SPECTATEUR${s.id===state.hostId?' · HÔTE':''}</small></span><i class="${s.connected?'online':''}"></i></div>`).join('');$('waitingPlayers').innerHTML=spectators+state.players.map(p=>`<div class="waiting-player"><img src="assets/characters/${characterFile(p.character)}" alt=""><span><b>${esc(p.name)}</b><small>${esc(p.character)}${p.id===state.hostId?' · HÔTE':''}</small></span><i class="${p.connected?'online':''}"></i></div>`).join('');const host=state.viewerId===state.hostId;$('onlineStartButton').classList.toggle('hidden',!host);$('waitingHint').textContent=host?(state.players.length<2?'En attente d’au moins deux joueurs actifs…':`${state.players.length} joueurs prêts. Vous pouvez lancer la partie.`):"L’hôte lancera la partie lorsque tout le monde sera prêt."}
function renderChat(){if(!state)return;const box=$('chatMessages'),atBottom=box.scrollHeight-box.scrollTop-box.clientHeight<40;box.innerHTML=state.chat.map(m=>`<div class="chat-message ${m.role==='spectator'?'spectator':''}"><b>${esc(m.sender)}</b><span>${esc(m.text)}</span></div>`).join('')||'<p class="chat-empty">Le chat est ouvert. Soyez le premier à parler.</p>';if(atBottom)box.scrollTop=box.scrollHeight;if(state.chat.length>lastChatCount&&$('chatPanel').classList.contains('collapsed'))$('chatBadge').textContent=String(state.chat.length-lastChatCount);lastChatCount=state.chat.length}
function legalIds(){const me=state.players.find(p=>p.id===state.viewerId);if(!me||state.phase!=='play'||state.players[state.turn]?.id!==state.viewerId)return new Set();if(!state.leadColor)return new Set(me.dice.map(d=>d.id));const matching=me.dice.filter(d=>d.color===state.leadColor);return new Set((matching.length?[...matching,...me.dice.filter(d=>special(d.color))]:me.dice).map(d=>d.id))}
function renderGame(){const legal=legalIds();$('roundValue').textContent=`${state.round} / ${state.totalRounds}`;$('trickValue').textContent=`${state.trick} / ${state.round}`;$('leadColor').textContent=state.leadColor?COLORS[state.leadColor].toUpperCase():'—';$('phaseValue').textContent={bids:'PARIS',play:'LANCER',result:'RÉSULTAT',over:'TERMINÉ'}[state.phase]||state.phase;$('game').dataset.phase=state.phase;$('playersGrid').dataset.count=state.players.length;
  $('playersGrid').innerHTML=state.players.map((p,i)=>{const active=i===state.turn&&['bids','play'].includes(state.phase),mine=p.id===state.viewerId,side=i%2?'right-avatar':'left-avatar';return `<article class="player-card ${active?'active':''} ${mine?'is-me':''}"><div class="turn-indicator"><span>${mine?'À VOUS DE JOUER':'À SON TOUR'}</span><b>▼</b></div><div class="avatar-zone ${side}" aria-hidden="true"><div class="avatar-aura"></div><img class="character-sprite" src="assets/characters/${characterFile(p.character)}" alt=""><div class="avatar-shadow"></div></div><div class="player-head"><h3>${esc(p.name)}</h3><strong>${p.score}</strong></div><div class="metrics"><span>PARI <b>${p.bid??'—'}</b></span><span>PLIS <b>${p.tricks}</b></span>${mine?'<span>VOUS</span>':''}</div><div class="dice-rack">${p.dice.map(d=>dieHTML(d,legal.has(d.id))).join('')}</div>${p.connected?'':'<small class="disconnected">HORS CONNEXION</small>'}</article>`}).join('');document.querySelectorAll('[data-die]').forEach(el=>el.onclick=()=>send('play',{dieId:el.dataset.die}));$('playedDice').innerHTML=state.played.map(x=>`<div class="played-slot">${dieHTML(x.die)}<small>${esc(state.players[x.player].name)}</small></div>`).join('');$('bidControls').innerHTML='';$('nextButton').classList.add('hidden');$('resetButton').classList.add('hidden');$('newRoomButton').classList.add('hidden');const turnPlayer=state.players[state.turn],myTurn=turnPlayer?.id===state.viewerId;
  if(state.phase==='bids'){$('message').innerHTML=`<strong>PARI DE ${esc(turnPlayer.name.toUpperCase())}</strong><br><span>${myTurn?'Choisissez le nombre de plis que vous allez remporter.':'En attente de son pari…'}</span>`;if(myTurn){$('bidControls').innerHTML=Array.from({length:state.round+1},(_,n)=>`<button data-bid="${n}">${n}</button>`).join('');document.querySelectorAll('[data-bid]').forEach(el=>el.onclick=()=>send('bid',{bid:+el.dataset.bid}))}}
  if(state.phase==='play')$('message').innerHTML=`<strong>AU TOUR DE ${esc(turnPlayer.name.toUpperCase())}</strong><br><span>${myTurn?'Choisissez maintenant l’un de vos dés illuminés.':'Son choix apparaîtra ici.'}</span>`;if(state.phase==='result'){$('message').textContent=`Pli remporté par ${state.players[state.leader].name}.`;$('nextButton').classList.toggle('hidden',state.players[state.leader].id!==state.viewerId)}if(state.phase==='over'){const max=Math.max(...state.players.map(p=>p.score)),winners=state.players.filter(p=>p.score===max).map(p=>p.name);$('message').textContent=winners.length>1?`Égalité : ${winners.join(' et ')}.`:`${winners[0]} remporte le duel !`;$('playedDice').innerHTML='<strong>DUEL TERMINÉ</strong>';const host=state.viewerId===state.hostId;$('resetButton').classList.toggle('hidden',!host);$('newRoomButton').classList.toggle('hidden',!host)}}
function init(){
  const options=CHARACTERS.map(([name],i)=>`<option value="${i}">${name}</option>`).join('');$('characterSelect').innerHTML=options;
  $('createButton').onclick=createRoom;$('organizerButton').onclick=createOrganizer;$('joinButton').onclick=joinRoom;$('roomCodeInput').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,'');
  $('onlineStartButton').onclick=()=>send('start');$('nextButton').onclick=()=>send('next');$('resetButton').onclick=()=>send('reset');$('newRoomButton').onclick=()=>send('newRoom');$('leaveButton').onclick=()=>{localStorage.removeItem('duel-session');session=null;state=null;location.reload()};$('copyCode').onclick=async()=>{await navigator.clipboard.writeText(state.code);$('copyCode').textContent='COPIÉ !';setTimeout(()=>$('copyCode').textContent=state.code,1000)};
  $('chatHeader').onclick=()=>{$('chatPanel').classList.toggle('collapsed');$('chatBadge').textContent=''};
  $('chatForm').onsubmit=e=>{e.preventDefault();const text=$('chatInput').value.trim();if(text){send('chat',{text});$('chatInput').value=''}};
  $('rulesButton').onclick=()=>$('rulesDialog').showModal();$('closeRules').onclick=()=>$('rulesDialog').close();$('legend').innerHTML=['brown','green','blue'].map(c=>`<div class="legend-item">${dieHTML({color:c,face:'symbol'})}<span>${COLORS[c]}</span></div>`).join('');connect()
}
init();
