create table if not exists public.duel_results (
  id bigint generated by default as identity primary key,
  game_id text not null,
  character text not null,
  result text not null check (result in ('win', 'loss', 'draw')),
  score integer not null default 0,
  tricks integer not null default 0,
  played_at timestamptz not null default now()
);

create index if not exists duel_results_played_at_idx on public.duel_results (played_at desc);
create index if not exists duel_results_character_idx on public.duel_results (character);

alter table public.duel_results enable row level security;

-- Sauvegarde privée des parties en cours. Cette table ne possède aucune
-- politique publique : seule la clé secrète utilisée par le serveur Render
-- peut lire ou modifier son contenu.
create table if not exists public.duel_active_games (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists duel_active_games_updated_at_idx
  on public.duel_active_games (updated_at desc);

alter table public.duel_active_games enable row level security;

-- Abonnements Web Push privés. L'adresse d'abonnement et ses clés ne doivent
-- jamais être exposées au navigateur d'un autre joueur : seul Render y accède
-- avec la clé service_role.
create table if not exists public.duel_push_subscriptions (
  endpoint text primary key,
  subscription jsonb not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists duel_push_subscriptions_updated_at_idx
  on public.duel_push_subscriptions (updated_at desc);

alter table public.duel_push_subscriptions enable row level security;
