create table if not exists public.duel_results (
  id bigint generated by default as identity primary key,
  game_id text not null,
  character text not null,
  result text not null check (result in ('win', 'loss', 'draw')),
  score integer not null default 0,
  tricks integer not null default 0,
  played_at timestamptz not null default now()
);

create index if not exists duel_results_played_at_idx on public.duel_results (played_at desc);
create index if not exists duel_results_character_idx on public.duel_results (character);

alter table public.duel_results enable row level security;
