create table if not exists public.duel_results (
  id bigint generated by default as identity primary key,
  game_id text not null,
  character text not null,
  result text not null check (result in ('win', 'loss', 'draw')),
  score integer not null default 0,
  tricks integer not null default 0,
  played_at timestamptz not null default now()
);

create index if not exists duel_results_played_at_idx on public.duel_results (played_at desc);
create index if not exists duel_results_character_idx on public.duel_results (character);

alter table public.duel_results enable row level security;

-- Sauvegarde privée des parties en cours. Cette table ne possède aucune
-- politique publique : seule la clé secrète utilisée par le serveur Render
-- peut lire ou modifier son contenu.
create table if not exists public.duel_active_games (
  code text primary key,
  state jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists duel_active_games_updated_at_idx
  on public.duel_active_games (updated_at desc);

alter table public.duel_active_games enable row level security;

-- Écriture atomique d'un état de partie. Une ancienne instance Render ne peut
-- plus remplacer une sauvegarde possédant une révision plus récente.
create or replace function public.duel_save_active_game(
  p_code text,
  p_state jsonb,
  p_revision bigint
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  saved boolean;
begin
  insert into public.duel_active_games(code,state,updated_at)
  values(p_code,p_state,now())
  on conflict(code) do update
    set state=excluded.state,updated_at=excluded.updated_at
    where coalesce((public.duel_active_games.state->>'revision')::bigint,0) < p_revision
  returning true into saved;
  return coalesce(saved,false);
end;
$$;

revoke all on function public.duel_save_active_game(text,jsonb,bigint) from public, anon, authenticated;
grant execute on function public.duel_save_active_game(text,jsonb,bigint) to service_role;

-- Abonnements Web Push privés. L'adresse d'abonnement et ses clés ne doivent
-- jamais être exposées au navigateur d'un autre joueur : seul Render y accède
-- avec la clé service_role.
create table if not exists public.duel_push_subscriptions (
  endpoint text primary key,
  subscription jsonb not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists duel_push_subscriptions_updated_at_idx
  on public.duel_push_subscriptions (updated_at desc);

alter table public.duel_push_subscriptions enable row level security;
